# Generated by Django 3.2.6 on 2021-12-04 12:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20211204_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
