# Generated by Django 3.2.6 on 2021-12-04 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_post_post_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dp',
            field=models.ImageField(default='F:\\Minor\\mp\x07pp\\static\\img\x07vatar7.png', null=True, upload_to='dp', verbose_name='dp'),
        ),
    ]
