# Generated by Django 3.2.6 on 2021-12-04 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_profile_dp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dp',
            field=models.ImageField(null=True, upload_to='dp', verbose_name='dp'),
        ),
    ]
