# Generated by Django 3.2.6 on 2021-12-05 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20211205_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='dp',
        ),
        
    ]
