# Generated by Django 3.2.6 on 2021-12-05 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20211205_2318'),
    ]

    operations = [
        
    ]
