# Generated by Django 3.2.6 on 2021-12-05 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_post_p_dp'),
    ]

    operations = [
    ]
