# Generated by Django 3.2.6 on 2021-12-05 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_post_p_dp'),
    ]

    operations = [
        
    ]
