# Generated by Django 3.2.6 on 2021-12-07 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ImageField(default=0, upload_to=''),
        ),
    ]
