# Generated by Django 3.2.6 on 2021-12-10 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_comment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comnt',
            field=models.IntegerField(default=0),
        ),
    ]
